# Jekyll Configuration
#
title: Durobeach
email: admin@durobeach.com
description: Durobeach Hotel and Kite Center
baseurl: ""
url: "http://durobeach.github.io"
twitter_username: durobeach
github_username:  durobeach
permalink: pretty
defaults:
  - scope:
      path: ""
    values:
      layout: page
      parent: ""
      order: 0

# Build settings
markdown: kramdown
gems:
  - jekyll-redirect-from
exclude:
  - Gemfile
  - Gemfile.lock

# Sass assets
sass:
  sass_dir: _sass
  style: compressed
